<?php

namespace App\Enums;

enum FeedbackCategory: string
{
    case FEATURE_SUGGESTION = 'FEATURE_SUGGESTION';
    case USABILITY_ISSUE = 'USABILITY_ISSUE';
    case APP_PERFORMANCE = 'APP_PERFORMANCE';
    case ROUTE_ACCURACY = 'ROUTE_ACCURACY';
    case GENERAL_EXPERIENCE = 'GENERAL_EXPERIENCE';
    case ADDITIONAL_SUGGESTIONS = 'ADDITIONAL_SUGGESTIONS';
}